# Generated by Django 5.1.6 on 2025-02-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_type', models.CharField(choices=[('purchase_invoice', 'Purchase Invoice'), ('expense_invoice', 'Expense Invoice'), ('investment_invoice', 'Investment Invoice')], max_length=50)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.invoicestate')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='TaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_type', models.CharField(max_length=100)),
                ('tax_regime', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product_type', 'tax_regime', 'country'), name='unique_tax_policy')],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_policies',
            field=models.ManyToManyField(blank=True, to='invoice_app.taxpolicy'),
        ),
    ]
