# Generated by Django 5.1.6 on 2025-02-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_initial'),
    ]

    operations = [
    ]
