# Generated by Django 5.1.6 on 2025-02-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_initial'),
    ]

    operations = [
    ]
