# Generated by Django 5.1.6 on 2025-02-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
    ]
